### ISSUE TITLE
testing contract as a different user

### ISSUE THREAD

**Issue by tansaku** [trufflesuite/trufflesuite.com#1008]
apologies if this is the wrong place for this question, but I am inferring that a test will implictly be taking place as a particular user/account.  For example in a test like:

```js
  const instance = await MyCoin.deployed()
  const accountTwo = accounts[1]
  const amount = 100
  await instance.transfer(accountTwo, amount)
```

then the transfer will take place from accounts[0] to accounts[1], with the implication that the user/account doing the transfer is in charge of account[0].

Is there some way to make that explicit and/or change?  So for example that we could write a test that would operate as a user in charge of some other account?

**Comment by eggplantzzz** [comment]
For contract methods (when using @truffle/contract objects), there is always an implicit final argument. So for example, say your Solidity function takes 2 arguments, there is always an implicit 3rd "transaction params" argument. These correspond to web3's transaction options (https://web3js.readthedocs.io/en/v1.2.7/web3-eth-contract.html#options) and, as you may guess, set the options for the transaction. You can choose to include this final argument (it is optional and takes the form of an object with named keys) and explicitly set values that you would like. You can see an example of this [here](https://www.trufflesuite.com/docs/truffle/getting-started/interacting-with-your-contracts#making-a-transaction) in the Truffle docs.

Does that make sense?  By default Truffle uses `accounts[0]` for the `from` parameter in transactions where the user doesn't enter in their own `from`. So in your example above, `instance.transfer` is being executed with `accounts[0]` being the sender. You can change this by supplying a third argument with a different `from` address. Let me know if this is not clear enough and I can try to clarify further.

**Comment by tansaku** [comment]
hi @eggplantzzz big thanks for that - exactly what I wanted to know.  Tests all passing now :-)
