### ISSUE TITLE
Mainline integration of Tezos in Truffle status

### ISSUE THREAD

**Issue by Reudlak** [trufflesuite/trufflesuite.com#1037]
Hi, over a year ago you stated in this article on 2020-4-15 - https://www.trufflesuite.com/blog/branching-out-announcing-tezos-support-in-truffle that you want to add

1) Mainline integration of Tezos in Truffle
1) a Tezos-flavored Ganache
2) full support for SmartPy

I cant find anything about it, whats the status?

**Comment by eggplantzzz** [comment]
Hey @Reudlak, thanks for the inquiry! This work is still in progress though I'm not really sure how soon we expect this work to be done. The best I can tell you for now is to keep watch on the Truffle PRs/release notes to check for updates. Thanks!

**Comment by Reudlak** [comment]
Ok thanks I will keep watching!

**Comment by BearCooder** [comment]
Hello @haltman-at & @fainashalts can you please make a statement as to why Tezos support is not a priority anymore? To be honest it leaves a bad taste after the big announcement od Tezos support in Truffle ([Twitter](https://twitter.com/trufflesuite/status/1250486441341304835) and [Blogpost](https://trufflesuite.com/blog/branching-out-announcing-tezos-support-in-truffle/)) over two years ago. The funny thing is the support didnt last long, less than a year later Truffle started to ghost all issues and update requests on github or stated to do it later.. why the sudden change back then?

At least make either make it official and announce that you are not supporting Tezos anymore or at least update Tezos Truffle to current protocol standard. I dont know maybe its a failure on the communication side, maybe Truffle @tcoulter and Tezos Foundation @drchrispinnock need to talk but the current state is unfortunate.
