### ISSUE TITLE
The download button redirects to the wrong release page

### ISSUE THREAD

**Issue by HarsimranVirk** [trufflesuite/trufflesuite.com#1051]
The issue here is with the site, the download button redirects to [ganache release page](https://github.com/trufflesuite/ganache/releases/tag/2.13.2), instead of [ganache-ui release page](https://github.com/trufflesuite/ganache-ui/releases/tag/v2.5.4).

Even though the code here seems fine, I'm not sure why it doesn't reflect on the actual website.
https://github.com/trufflesuite/trufflesuite.com/blob/01939031c759e064ff42670d9149fddaabf32286/src/ganache.html#L75-L86

**Comment by davidmurdoch** [comment]
Thanks for opening this issue. This was fixed in https://github.com/trufflesuite/trufflesuite.com/pull/1048 and deployed this morning!
