### ISSUE TITLE
'call is not a function error' in Pet-Shop tutorial

### ISSUE THREAD

**Issue by plm75** [trufflesuite/trufflesuite.com#106]
I get this error in the browser console when running the app and the UI does not reflect past transactions (ie adopt button is not disabled).

Removing the 'call()' and simply using `return adoptionInstance.getAdopters()` updates the UI during the initial page load but does not update after a new transaction.

**Comment by DiscRiskandBisque** [comment]
Hey @plm75! Sorry for the extremely late reply. I'm closing this due to its age, and the fact that the Pet Shop tutorial has gone through a few iterations since 2018. If this issue persists please re-open, thanks!
