### ISSUE TITLE
pet shop: adoption not possible

### ISSUE THREAD

**Issue by FabiolaBusch** [trufflesuite/trufflesuite.com#107]
I followed all the steps in the [pet-shop tutorial](http://truffleframework.com/tutorials/pet-shop) and Pete's pet shop is presented nicely, but when I click on 'Adopt' and confirm the transaction on MetaMask, MetaMask gets stuck. 

![meta1](https://user-images.githubusercontent.com/19983973/38860593-d2132b24-4230-11e8-9603-66eed25a6918.png)

I close MetaMask, open it again and the transaction seems to be approved, but no ether was removed. 

![meta2](https://user-images.githubusercontent.com/19983973/38860598-d61a7628-4230-11e8-947a-5e79cdd4f0c0.png)

But the adopt-button does not change to 'Success'. Adding 

`console.log(adoptions)` 

in App.js, I only see an array filled with zero addresses. 

Ganache is running, the contract was deployed successfully, a few ethers were paid by the first account in Ganache and MetaMask is on `HTTP://127.0.0.1:7545` just like Ganache, too. `npm run dev` also works fine. Important to mention: the very first time I set the whole system up and adopted pets everything worked! I removed build files before running it again, but that did not help.

**Comment by FabiolaBusch** [comment]
Oh, solved it. 

I re-initated Ganache with a new seed phrase, deleted build files, ran `truffle compile`, `truffle migrate --restart` and `npm run dev` and then I could adopt pets successfully. 

Has anyone an explanation why it didn't work with the seed (e.g. the local blockchain) which I used previously?

**Comment by DiscRiskandBisque** [comment]
Hi @FabiolaBusch! I apologize on behalf of the whole team for the extremely belated reply. I'm glad you were able to figure it out! If this issue pops up again in the future, don't hesitate to open a new issue.
