### ISSUE TITLE
Fix Tutorial: Getting Started With Drizzle and React

### ISSUE THREAD

**Issue by fainashalts** [trufflesuite/trufflesuite.com#1074]
[This tutorial](https://www.trufflesuite.com/guides/getting-started-with-drizzle-and-react) needs some fixes and updates.This issue arose from the tutorial review issue, trufflesuite/issue-target-tmp#1.

**Issues To Fix**

- Add a link to redux for newer users who may not be familiar
- fix link to petshop tutorial
- update versions where possible: solidity, node, truffle (especially *node* -- currently calls for v8 which we don't support
- Update Solidity version in `MyStringStore.sol`
- “This will spawn a new blockchain that listens on 127.0.0.1:9545 by default": fix port to be correct (isn't it 8545?)
- Fix [resolving name conflicts in Windows] link
- Fix link to [Truffle Documentation]
- “We need to bring the contracts `in` our build folder inside source” -- change to `from`
- client/src/App.js file doesn’t look anything like what’s in the tutorial, which may just be a version issue? But may be worth pointing out. Got some errors when attempting to compile regarding imports/exports
    * App not exported in App Component
    * Don’t need `import * as serviceWorker from ‘./serviceWorker’`;
    * **** tutorial does not adequately explain how to set up the config to work with web sockets: it should look something like this (change the port and set websockets to true):
    
```
 development: {
      host: "127.0.0.1",     // Localhost (default: none)
      port: 8545,            // Standard Ethereum port (default: none)
      network_id: "*",
      websockets: true     // Any network (default: none)
     },
```

    * Update code screenshots to match output from current versions
    * “the return value of ~~the~~ subscribe() to a class variable…”
    * Conclusion says to go to “drizzle-react” with a link, but that link actually goes to a codebase called https://github.com/trufflesuite/drizzle-react-legacy ;  perhaps there is a better place to point users?

**Comment by dkillen** [comment]
Fixed in [PR #1189](https://github.com/trufflesuite/trufflesuite.com/pull/1189)
