### ISSUE TITLE
Fix Tutorial: Drizzle and Contract Events

### ISSUE THREAD

**Issue by fainashalts** [trufflesuite/trufflesuite.com#1076]
[This tutorial](https://www.trufflesuite.com/guides/drizzle-and-contract-events) needs some updates. This issue came about as a result of work on trufflesuite/issue-target-tmp#1. 

*Issues to Fix*
- Fix links in blue boxes!
- Typo: “Processes each dispatched action~~s~~ before passing them to Reducers…”
- Need to be a bit more clear about where in the code certain code snippets go — assume complete lack of experience with react from the tutorial user
- Connecting to the `store` via this code is not working: 
```
// App.js
...
import store from './middleware'
...
<DrizzleProvider store={store} options={drizzleOptions}>
...
```

Overall this tutorial is pretty up to date! Shouldn't take long to make these small fixes.

**Comment by dkillen** [comment]
@fainashalts - I have a question about your last issue here. Are you referring to the code in the drizzle-event-demo repo as opposed to the tutorial itself? Following the tutorial doesn't result in that code. However, I noticed that it is present in the demo code which is referred to by the tutorial.

**Comment by fainashalts** [comment]
Oh! Sorry @dkillen its been nearly a year since I audited all the tutorials, but I think you are right. Its the demo code that isn't working. If its an easy fix, do you think you could update the demo? If its not an easy fix, perhaps you can add a to-do to the dev rel doc so it doesn't get lost? Thanks!
