### ISSUE TITLE
Pet-Shop: Success Button not showing up dynamically

### ISSUE THREAD

**Issue by samir-85** [trufflesuite/trufflesuite.com#109]
Hi everyone,

I just tested your pet shop tutorial which is really nice.

I noticed that when I adopt a pet, the success button is not showing immediately. Instead I need to refresh the web page to see the success button.

Somehow the entry in _adopters_ is still _0x0000000000000000000000000000000000000000_ during the markadopted() call. However sind _markadopted()_ is executed as promise after the _adop()_ transaction, I would expect that the _adopters_ entry is already changed and therefore the button would be updated accordingly.

Regards
Samir

**Comment by ItIsAMess** [comment]
Hi Samir,

I encountered exactly the same problem. My guess is that the contract instance is loaded before the contract is updated with the new account, causing the old data to be used for the markAdopted() function. 

Best practice would probably be to reload the contract instance and its data after the contract is updated, but I have no clue how to do that in this promise chain. 

I have a workaround though. My workaround for now is to pass on the petId as a parameter to the markAdopted function and adding an additional line of code after the already existing for() loop, which dynamically disables the button that was clicked on as well: 

`$('.panel-pet').eq(petId).find('button').text('Success').attr('disabled', true);`

Passing on the petId would be done by changing one line in the handleAdopt function:

`return App.markAdopted();` 

to:

`return App.markAdopted(petId);`

And by changing the receivable parameters of markAdopted to:

`markAdopted: function(petId)`

**Comment by DiscRiskandBisque** [comment]
Hey @samir-85! Sorry for the extremely late reply. I'm closing this due to its age, and the fact that the Pet Shop tutorial has gone through a few iterations since 2018. If this issue persists please re-open, thanks!
