### ISSUE TITLE
Doc site is broken

### ISSUE THREAD

**Issue by jjbully** [trufflesuite/trufflesuite.com#1092]
the doc site is broken

https://trufflesuite.com/guides/ethereum-overview

**Comment by kevinbluer** [comment]
Oooh thanks for raising this @jjbully! We just did a migration to a new static site generator (mkdocs / material) and while I remember this getting fixed, it looks looks like it must have reverted somewhere along the way. We'll get on it ASAP 👍

**Comment by kevinbluer** [comment]
Should be now resolved @jjbully (https://trufflesuite.com/guides/ethereum-overview), thanks so much again for raising! Closing for now although feel free to re-open / raise any other issues.

Have a great weekend 🥳
