### ISSUE TITLE
Remove link underlining in Safari (desktop and mobile)

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/trufflesuite.com#1096]
Example below...

<img width="572" alt="136441166-8f3fde69-6a67-4a06-b56a-7c91d2d1d6e0" src="https://user-images.githubusercontent.com/210755/144656247-f5ddcb87-285c-4dd9-b83a-b4f8a27e94b7.png">

**Comment by sj00coder** [comment]
Hey, Is this issue still valid ? Now it has different text at the position and it is underlined in every browser.
Please correct me if I misunderstood anything.
Thanks
<img width="1440" alt="Screenshot 2023-06-27 at 12 07 55 AM" src="https://github.com/trufflesuite/trufflesuite.com/assets/65244030/1c0ef6d5-5697-4480-9130-68eb6b0ae9a4">
<img width="1440" alt="Screenshot 2023-06-27 at 12 06 18 AM" src="https://github.com/trufflesuite/trufflesuite.com/assets/65244030/57e6961f-a280-495a-a817-b97aa684d275">

**Comment by jeffsmale90** [comment]
I'm pretty confident that this issue is no longer relevant. As you pointed out, the rendering is consistent between different browsers. 

@davidmurdoch feel free to reopen if you know something that we don't.
