### ISSUE TITLE
Re: Building Robust Smart Contracts With Openzeppelin

### ISSUE THREAD

**Issue by zulhfreelancer** [trufflesuite/trufflesuite.com#111]
Hi,

I'm following [this tutorial](http://truffleframework.com/tutorials/robust-smart-contracts-with-openzeppelin) and I faced some problems with it. But, I managed to solve it after Googling here and there.

I shared my workarounds in this thread:
https://twitter.com/zulhhandyplast/status/990281602268774400

Hopefully one of you can update the tutorial to help others especially newbies to follow it better without any issues.

Thank you.

**Comment by bmmpxf** [comment]
Thanks @zulhfreelancer ! We hadn't caught that they had renamed their package and repository. I've updated our tutorial with commit https://github.com/trufflesuite/trufflesuite.com/commit/96c71518aff15ea82c65001cf2a7c59e5d007e93.
