### ISSUE TITLE
Some pages on https://trufflesuite.com/ give 404's 

### ISSUE THREAD

**Issue by LoveKosmos** [trufflesuite/trufflesuite.com#1135]
When selecting the **BOXES** tab on [trufflesuite.com/index.html](https://trufflesuite.com/index.html) and clicking on **CREATE A BOX**

On [https://trufflesuite.com/docs/truffle/advanced/creating-a-truffle-box.html](https://trufflesuite.com/docs/truffle/advanced/creating-a-truffle-box.html) page click on the _**'download the files here'**_ link which will redirect you to the 404 ([https://trufflesuite.com/files/truffle-box-essentials.zip](https://trufflesuite.com/files/truffle-box-essentials.zip))

On [https://trufflesuite.com/boxes/tutorialtoken/](https://trufflesuite.com/boxes/tutorialtoken/) page click the _**'Open Zeppelin (TutorialToken) tutorial'**_ link which will redirect you to the 404 ([https://trufflesuite.com/tutorials/robust-smart-contracts-with-openzeppelin](https://trufflesuite.com/tutorials/robust-smart-contracts-with-openzeppelin))

**Sample of 404 below:** 

![Screen Shot 2022-01-10 at 4 50 49 PM](https://user-images.githubusercontent.com/12563620/148844836-d5b0d195-6424-4e6f-919e-bd108e2a1ca6.png)

**Comment by kevinbluer** [comment]
Awesome thanks for raising @LoveKosmos! We'll get on with getting these resolved 👍
