### ISSUE TITLE
Download button (Windows) for Ganache is not working

### ISSUE THREAD

**Issue by FlaviuWeb3** [trufflesuite/trufflesuite.com#1138]
When clicking the Download (Windows) button https://trufflesuite.com/ganache, the link is not starting any download (no redirect)

<img width="1440" alt="Screenshot 2022-01-11 at 16 46 36" src="https://user-images.githubusercontent.com/97533870/148964548-f574b65e-4bca-40e7-a4f3-17b80bcf795a.png">

**Comment by davidmurdoch** [comment]
@kevinbluer is fixing this and will have a fix out for this ASAP!
