### ISSUE TITLE
Found 83 links on trufflesuite.com that 404

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/trufflesuite.com#1144]
See attached report:

[links.txt](https://github.com/trufflesuite/trufflesuite.com/files/7865087/links.txt)

**Comment by kevinbluer** [comment]
Out of interest when did you run this, as this [PR](https://github.com/trufflesuite/trufflesuite.com/pull/1137) got merged ~4 hours ago that fixed a bunch?

**Comment by davidmurdoch** [comment]
I'll run it again now to make sure.

**Comment by davidmurdoch** [comment]
[siteerrors.log](https://github.com/trufflesuite/trufflesuite.com/files/7866227/siteerrors.log)

82 errors found.

**Comment by Neurone** [comment]
They should be all fixed now (#1145), but some resources are actually missing from the repo at all.

**Comment by kevinbluer** [comment]
Thanks again @Neurone! @davidmurdoch this should be all good to close when you have a moment.

**Comment by lsqproduction** [comment]
Fixed in #1145 Thanks again @Neurone for getting to this.
