### ISSUE TITLE
BUG - Menu not clickable

### ISSUE THREAD

**Issue by warstrolo** [trufflesuite/trufflesuite.com#1171]
![image](https://user-images.githubusercontent.com/58334832/153722588-00c6046d-0662-4dbe-9806-3ef492c13f25.png)

the ganache block are making the menu unclickable

**Comment by warstrolo** [comment]
Impacted url : https://trufflesuite.com/ganache/

**Comment by gnidan** [comment]
I believe this is now fixed. @warstrolo would you mind please confirming?

(Thanks for bringing this to our attention!)

**Comment by warstrolo** [comment]
Yes good 😊

Btw thanks for the amazing job you are doing with this project,

I did not see but i'm looking for a way top deploy an etherum proof of authority on k8s do you know how Can i do that ?

Big thanks and waiting for your reply 😁

**Comment by eggplantzzz** [comment]
Thanks for reporting this @warstrolo, closing this for issue maintenance!
