### ISSUE TITLE
Many links on https://trufflesuite.com/events/ are broken

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/trufflesuite.com#1199]

**Comment by dongmingh** [comment]
@leeftk is this something you can look into?

**Comment by leeftk** [comment]
I don't understand enough about the issue to be the one to own this. But I'll gladly pair with someone who has a bit more context on what's going on and tackle it with them.

**Comment by davidmurdoch** [comment]
@leeftk a bunch of the "Watch Now" buttons don't go anywhere because they are broken, mostly because we lost control of the `trfl.co` domain that was used at the time to redirect to the actual destination. We lost this domain last year, and all the links that went with it.
