### ISSUE TITLE
Privacy Policy may be too broad

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/trufflesuite.com#1208]
> This Policy applies to the Sites, applications, products and services (collectively, “Services”) on or in which it is posted, linked, or referenced.

https://trufflesuite.com/policy/

We link to and reference all sorts of things that we don't control, like node, npm, github, microsoft, starbucks, filecoin, ipfs, etc. I don't think we should claim that our policy applies to those "Services", which is what it sounds like our policy is attempting to do. :-)

But I don't speak legalese by any means, so maybe I'm wrong?

**Comment by kevinweaver** [comment]
From the legal team: 

> The wording is accurate and standard - it refers to sites and apps where the Truffle Privacy Policy is itself posted (e.g. the Truffle website) rather than sites and apps that we are simply linking to. Our privacy policy isn't actually posted on Filecoin, IPFS etc. and we do not claim that it applies to the entirety of the Filecoin, IPFS services (although the data transfer elements of our Privacy Policy may in certain cases apply to those services). I hope that clears things up. Happy to hop on a call to chat through if needs be. 

Closing this, as it sounds like a non-issue!
