### ISSUE TITLE
OpenZeppelin smart contract tutorial: Need to import accounts to MetaMask

### ISSUE THREAD

**Issue by btphan95** [trufflesuite/trufflesuite.com#121]
Hello, I am working on the Robust Smart Contracts with OpenZeppelin tutorial. I created the TutorialToken smart contract, and after deploying the smart contract onto a Ganache blockchain, I tried to access my accounts on MetaMask. However, the tutorial gets lost here, because it doesn't specify the user to import the accounts in Ganache into MetaMask using their private keys. Instead, it assumes that we use the account created in MetaMask, which is bad because that account doesn't hold any TutorialToken or Ethereum, so it's useless for the rest of the tutorial. So, this tutorial needs to add a section on how to import accounts into MetaMask. 

On another note, I'm transferring TutorialTokens between accounts, but I can't transfer the full balance from one account to another, instead the transaction fails. I can transfer up to (balance - 1), leaving one TT. Why is this happening?

**Comment by bmmpxf** [comment]
Hi there @btphan95 . Thanks for the report. Lots of good stuff in there.

You shouldn't need to "Import Account" in MetaMask. All you need to do is enter the seed phrase in Ganache, and make sure you're on the appropriate network (http://127.0.0.1:7545). To add more accounts from that seed phrase, you can select "Create Account". (You really only need two accounts to follow this tutorial.) So I don't see anything that needs to be changed there.

Now, as for your second issue, that was a very interesting one. I was able to reproduce it after some time. What clued us in is that if one sends all 12,000 TT from one account to the other, it will succeed, but if one has _some_ TT and the other account also has _some_ TT and one wants to offload all of it to the other account, the transaction will fail.

The short answer is that it's an out of gas error.

The slightly longer answer is that the estimateGas function in web3 (which MetaMask uses) is flawed; there is a gas refund for storage that goes from a non-zero value to a zero value, and the function doesn't pick this up, leading to a lower gas estimate than what is required. (When transferring all TT from one account to another, one value goes from non-zero to zero and the other vice versa, so the function is more accurate and so doesn't fail.)

I've added a default gas limit to the transfer function in our dapp as of https://github.com/truffle-box/tutorialtoken-box/commit/2ee38aa22ceb09d93ca1810cb5eed3e37f04c9b6. MetaMask will respect this value, and it should be more than enough to get through any transfer.

So you should be okay with token transfers now. Thanks for reporting!
