### ISSUE TITLE
Link githubs for truffle boxes

### ISSUE THREAD

**Issue by emilyJLin95** [trufflesuite/trufflesuite.com#1215]
Currently, the corresponding github repos are not linked for the various truffle boxes
There used to exist a righthand column for each page that included that

This issue is to add that back in

**Comment by kevinbluer** [comment]
Example of original view at the following: https://web.archive.org/web/20210227215354/https://www.trufflesuite.com/boxes/metacoin

![image](https://user-images.githubusercontent.com/210755/167508841-0453beb3-022f-4e72-ae15-75608a193a10.png)

**Comment by eggplantzzz** [comment]
Has this issue been resolved with #1250?

**Comment by cds-amal** [comment]
> Has this issue been resolved with #1250?

@emilyJLin95, @leeftk  ☝️

**Comment by emilyJLin95** [comment]
Yes! Though I would like to see the GitHub link on the actual box page itself rather than in the gallery view

**Comment by leeftk** [comment]
Yea this was resolved. To @emilyJLin95 's point above. I agree on this but we should probs open up a new issue for that separate to this imo.
