### ISSUE TITLE
Search component includes result not on website

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/trufflesuite.com#1217]
The [website](https://trufflesuite.com/docs/truffle/reference/configuration/) listed `Marymoor park` for `save intermediate` query! It also prioritized this result over possible truffle hits. The search component should constrain the search to truffle's site.  
<img width="1258" alt="Screen Shot 2022-04-09 at 7 11 58 AM" src="https://user-images.githubusercontent.com/2529600/162569563-34b23d8c-d673-4d57-80ce-616c688cdbbb.png">

**Comment by davidmurdoch** [comment]
Did it not link to https://github.com/trufflesuite/trufflesuite.com/blob/e16cf05a52273677d2d8dfcff750b6ca2de4752b/src/blog/the-best-things-to-do-in-seattle-during-trufflecon/index.md

**Comment by cds-amal** [comment]
Can we possibly exclude irrelevant results from search results. See: https://github.com/chrieke/mkdocs-exclude-search
