### ISSUE TITLE
Which one to judge?

### ISSUE THREAD

**Issue by 350050183** [trufflesuite/trufflesuite.com#124]
The article from http://truffleframework.com/tutorials/ethereum-overview introduced Alice hired Bob to build her patio, both sides transfer two eths in an escrow contract, when Bob finished his job, i want to know which one to judge the work quality? Alice? Bob? or the other third-party? you know, they can not believe in each other. the smart contract needs smart input to be "SMART". if the inputs are not qualified, then the results are not acceptable.

**Comment by DiscRiskandBisque** [comment]
Hi @350050183! This is very true and would be great for a more realistic version of this scenario. For the example provided in this article, we wanted to keep it very simple.
