### ISSUE TITLE
Pet-Shop the recipient address is invalid, no way to assign it!

### ISSUE THREAD

**Issue by qianguozheng** [trufflesuite/trufflesuite.com#126]
We need a place to set the recipient address is not contract address

**Comment by DiscRiskandBisque** [comment]
Hi @qianguozheng! First of all, apologies for the extremely late response. We wanted to keep this tutorial as simple as possible and using the defaults was part of that. For more information on setting the recipient address using web3, [see their docs](https://web3js.readthedocs.io/en/v1.2.4/).

If I've misunderstood and this is still an issue; please re-open or open a new one!
