### ISSUE TITLE
https://trufflesuite.com/docs/ganache/overview 404s

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/trufflesuite.com#1299]
It's linked to from ethereum.org, so we really need to fix it.

**Comment by kevinbluer** [comment]
Addressed in https://github.com/trufflesuite/trufflesuite.com/pull/1305 👌 

https://trufflesuite.com/docs/ganache/overview

**Comment by gnidan** [comment]
Looks like this is done, then! Thanks @kevinbluer!
