### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by emilyJLin95** [trufflesuite/trufflesuite.com#1334]
Truffle has dropped support for Node v12 and supports up to Node v18 now
should be able to just do a `npm i -g truffle` without worrying about being on the latest node (@cds-amal is that correct?)

**Comment by cds-amal** [comment]
Yes, we support Node v14, v16, and v18. We don't support the latest node, v19 and for installing Truffle, you can use the version of `npm` that ships with Node. No more pinning `npm` to v6.

**Comment by emilyJLin95** [comment]
PR: https://github.com/trufflesuite/trufflesuite.com/pull/1344

questions from @OnlyOneJMJQ 
https://github.com/trufflesuite/trufflesuite.com/issues/1341

**Comment by OnlyOneJMJQ** [comment]
Closing this issue because #1344 has been merged.
