### ISSUE TITLE
Remove deprecated networks from VScode

### ISSUE THREAD

**Issue by bgravenorst** [trufflesuite/trufflesuite.com#1337]
See: https://github.com/trufflesuite/vscode-ext/pull/250

**Comment by alexandratran** [comment]
The VSCode extension docs don't actually name the supported networks anywhere, so there is nothing to remove. There is only one minor mention that [you can deploy contracts to a testnet](https://trufflesuite.com/docs/vscode-ext/quickstart/#deploy-a-smart-contract-to-truffle).
