### ISSUE TITLE
Ethereum Overview is Outdated

### ISSUE THREAD

**Issue by OnlyOneJMJQ** [trufflesuite/trufflesuite.com#1339]
The [Ethereum Overview](https://trufflesuite.com/guides/ethereum-overview/) I wrote more than 5 years ago now had had a good run, but at this point it's very outdated. It still references Proof-of-Work consensus for Ethereum, doesn't get into Layer 2 networks or any other advancements made since its initial publishing.

We could either update it or remove it in favor of linking to other Ethereum/blockchain documentation in the places its currently linked.

**Comment by bgravenorst** [comment]
Perhaps we should link to the [official Ethereum documentation](https://ethereum.org/en/what-is-ethereum/), there's also some really [good content regarding layer 2s](https://ethereum.org/en/layer-2/)
