### ISSUE TITLE
Do we want to include Node.js installation instructions?

### ISSUE THREAD

**Issue by OnlyOneJMJQ** [trufflesuite/trufflesuite.com#1341]
By including our own Node.js installation instructions in How to > Install Truffle, we have to stay in sync with Node's own documentation. We could instead link to Node and nvm's installation instruction based on their OS.

That said, if the docs team is OK maintaining it that's fine by me, just thought it was something that could slip through the cracks easily so I wanted to bring it up.

**Comment by cliffoo** [comment]
Hey @OnlyOneJMJQ it looks like Emily has [put up a PR](https://github.com/trufflesuite/trufflesuite.com/issues/1334) for this. Does this issue need further work or does the PR suffice? Thanks!

**Comment by OnlyOneJMJQ** [comment]
Thanks for calling this out @cliffoo . I'll close this issue now as it's been addressed by #1344 .
