### ISSUE TITLE
pet adopt clicked succeed without wait for metamask approval

### ISSUE THREAD

**Issue by BlockWaving** [trufflesuite/trufflesuite.com#144]
followed tutorial all thru, web page is launched... metamask is configured account created, private net connected using ganache port number,  the eher value displayed in metamask correctly as in ganache account 1.

And then i went to click the pet adopt on web page, the button immediately changed to Success.  But  on the metamask side, there is nothing showed up.  Not a transaction prompt, no Approval click as tutorial said should be given.  But on web page side the pet showed as Success anyway.

After stop and relaunch the lite server and web page, all the previously Success button are properly appears.

So please let me know what could go wrong , why transactions didn't show up in MetaMask, and why transactions went thru without approval?

**Comment by DiscRiskandBisque** [comment]
Hey @BlockWaving! Sorry for the extremely late reply. I'm closing this due to its age, and the fact that the Pet Shop tutorial has gone through a few iterations since 2018. If this issue persists please re-open, thanks!
