### ISSUE TITLE
Ethereum Overview tutorial markdown is not parsed correctly

### ISSUE THREAD

**Issue by tjanson** [trufflesuite/trufflesuite.com#164]
The [_Ethereum Overview_ tutorial](https://truffleframework.com/tutorials/ethereum-overview) (with [this markdown source](https://github.com/trufflesuite/trufflesuite.com/blob/master/src/tutorials/ethereum-overview.md), which looks fine) is displayed incorrectly:

![truffleframework com_tutorials_ethereum-overview](https://user-images.githubusercontent.com/532114/44061289-0bf7af52-9f58-11e8-8466-acb9eb23eee6.png)

Might be due to this code, whatever markdown extension that is:

```md
{{#> breakout maxWidth=430 }}
  ![Centralized Database](/img/tutorials/ethereum-overview/db-server.png "Graphically represented, each arrow crossing a boundary of the main server box is a connection which requires trust")
{{/breakout}}
```

**Comment by DiscRiskandBisque** [comment]
Thanks @tjanson, and apologies for the extremely late response! This has since been fixed.
