### ISSUE TITLE
Port Error in tutorial "BUILDING & TESTING A FRONTEND APP WITH TRUFFLE 3.0" (?)

### ISSUE THREAD

**Issue by johnmw** [trufflesuite/trufflesuite.com#176]
Hi, I'm new to Truffle and just been trying to follow the above tutorial. 

I think I followed every step but the finished web app did not connect to Ganache.

Looking in the console, it falls back to port 9545 when there is no web3 provider.

The tutorial is using port 7545 for Ganache (the default) and does not mention you have to update your fallback port in index.js.

It just makes it a bit harder for newbs.

**Comment by Pupin3** [comment]
Hi and thanks for the tip, I haven't seen it before you mention it in your post!

But I am still having trouble to make it work! Everything looks ok, I compiled, migrated the contracts and then run "npm run dev" while my ganache were running on 7547 port which is also the port I use in the  truffle.js file. Still running the web app nothing happens and the status always displays the "Initiating transaction... (please wait)" message. 

Any ideas??

**Comment by gnidan** [comment]
Seems like this is potentially out of date. Does anyone know if this is still a problem? I'd be very surprised if anyone is still using Truffle v3. Let us know!

**Comment by DiscRiskandBisque** [comment]
Closing this for now, but if you'd still like to follow up @Pupin3, please open a new issue!
