### ISSUE TITLE
Cannot Open Truffle Console

### ISSUE THREAD

**Issue by TQWILLIS** [trufflesuite/trufflesuite.com#180]
Hi. I am a noob to Blockchain dev. I think got all my dependencies including ganache, metamask, etc. I think I had to have missed something bc when I go to build on or open truffle console, I get the following error. 
![unable to open truffle console](https://user-images.githubusercontent.com/29835798/44936110-6ee85700-ad41-11e8-8e99-8a1b909e6663.PNG)

I also get the following error when intializing truffle:
![truffle init error](https://user-images.githubusercontent.com/29835798/44936590-5aa55980-ad43-11e8-8f5e-c8849435f0c6.PNG)

Could someone tell by this error what I forgot to install or do?

Thank you. :)

**Comment by gnidan** [comment]
Hopefully you've found a workaround by now, but if not: rename `truffle.js` to `truffle-config.js`.

Looks like this isn't an issue with the docs themselves, so closing this for issue maintenance. Feel free to reply if there's anything else we can do to help here. Thank you!
