### ISSUE TITLE
link on this docs page:https://www.truffleframework.com/boxes/blueprint, is not linking to the correct place. 

### ISSUE THREAD

**Issue by balexander4** [trufflesuite/trufflesuite.com#183]
Link at the end of the docs text takes you back to the main truffle suite homepage. 

Expected Behavior: That it would take you to the the " Truffle Box section of our documentation " page as the link states.

https://www.truffleframework.com/boxes/blueprint

**Comment by gnidan** [comment]
Looks like this got fixed. Closing for issue maintenance. Thank you!
