### ISSUE TITLE
The first instance of the the Assert.sol link does not link to the expected page

### ISSUE THREAD

**Issue by balexander4** [trufflesuite/trufflesuite.com#184]
Link: https://truffleframework.com/docs/truffle/testing/writing-tests-in-solidity

Takes you to a git hub 404 page. As if the file does not exsist anymore or never did.

Expected Behavior: It would take you to the info for the Asset.sol code on github.

**Comment by vyomshm** [comment]
Hi @balexander4 , I noticed that too. Fix in in PR #228

**Comment by gnidan** [comment]
Seems like we can close this, then! Thanks @vyomshm and @balexander4!
