### ISSUE TITLE
truffle Test error

### ISSUE THREAD

**Issue by kbventures** [trufflesuite/trufflesuite.com#189]
PS D:\pet-shop-tutorial> truffle test
Using network 'development'.

Error parsing D:\pet-shop-tutorial\test\TestAdoption.sol: ParsedContract.sol:12:1: ParserError: Expected pragma, import directive or contract/interface/library definition.
function testUserCanAdoptPet() public {
^------^
Compilation failed. See above.
PS D:\pet-shop-tutorial>

**Comment by kbventures** [comment]
I am having similar problems with the metacoin box.

**Comment by vaibnak** [comment]
@kbventures can you please post your TestAdoption.sol file

**Comment by gnidan** [comment]
Hm, my hope is that this is no longer an issue. @vaibnak / @kbventures do either of you know?

We're doing issue maintenance here and would like to close this if there's nothing left to address here. Please advise!

**Comment by DiscRiskandBisque** [comment]
Closing this for now, but if anyone would like to follow-up please open a new issue--we welcome the feedback!
