### ISSUE TITLE
Sales on pet shop

### ISSUE THREAD

**Issue by corpoeureka** [trufflesuite/trufflesuite.com#194]
Hi, I would like to know how can I make a sell of the pet in the pet shop tutorial

**Comment by gnidan** [comment]
Hey @corpoeureka, do you still want to know how to do that? How much do you want for it?

Seems like there might be something actionable here for us to add to our tutorial, but not sure what that would be exactly. Let us know if this is something you still think would be valuable to mention. Thanks!

**Comment by DiscRiskandBisque** [comment]
Closing this for now, but if you'd like to follow-up @corpoeureka, feel free to open a new issue!
