### ISSUE TITLE
Pet-shop tutorial: Nothing happens when click Adopt button

### ISSUE THREAD

**Issue by manhlx3006** [trufflesuite/trufflesuite.com#200]
I have followed Pet-shop tutorial and nothing happens when click Adopt button. 
I found that the App.bindEvents() is not called after App is initialised.

What I did was calling App.bindEvents() after App.init(); or calling inside init function.

**Comment by dahifi** [comment]
Can you be more specific how you fixed it? I'm having same problem. 

The tutorial is a bit vague to how things should look when you're done with the editing. It looks like initContract calls it after the $.getJSON block we're supposed to add, but if that block is returning to App.markAdopted(), I'm not sure that bindEvents is even getting called.

**Comment by adrianmcli** [comment]
@dahifi 

> The tutorial is a bit vague to how things should look when you're done with the editing

Maybe we'll add a section to show the final form of the code. I haven't looked at the tutorial in a while, but I'll put that on my list of todos next week.

**Comment by vaibnak** [comment]
@manhlx3006 what browser are you using, I followed it and the Adopt button was working as expected.
My configurations -
Browser: Mozilla firefox 61.0.1
Os: Ubuntu 18.04

**Comment by manhlx3006** [comment]
I'm using
Browser: Version 70.0.3538.110
Os: macOS High Sierra 10.13.6

**Comment by adrianmcli** [comment]
@manhlx3006 would be helpful if you could push your project onto a github repo so we can try to run it and diagnose the problem.

**Comment by manhlx3006** [comment]
Hi, this is my repo https://github.com/manhlx3006/pet-shop-tutorial for sample of pet-shop-tutorial.

I have commented line 25 in https://github.com/manhlx3006/pet-shop-tutorial/blob/master/src/js/app.js. Uncomment will help to solve the issue but I'm not sure if it is a good solution. Thanks

**Comment by adrianmcli** [comment]
@manhlx3006 I see the issue. Yes you need to call `App.bindEvents()`, or else we are not listening to the click events of any of the buttons!

This should have been called in the last line of the `initContract` function, as you can see here: https://github.com/truffle-box/pet-shop-box/blob/master/src/js/app.js#L39

However, perhaps you copy and pasted over it when you were pasting in the code for that section? Also, it looks like you are not using the latest pet-shop box, as I do not see any async/await code in there.

**Comment by manhlx3006** [comment]
Yes, my version was around 2 months ago as you could see the date of reported issue.

**Comment by manhlx3006** [comment]
If it is fixed in the latest version then we could close the issue.

**Comment by adrianmcli** [comment]
Just make sure to call, `App.bindEvents()` somewhere in the code! Best of luck. Can re-open if you continue to have issues.
