### ISSUE TITLE
rename tutorial

### ISSUE THREAD

**Issue by MareoRaft** [trufflesuite/trufflesuite.com#203]
Could you change the title of the BUILDING & TESTING A FRONTEND APP WITH TRUFFLE 3.0 tutorial to be simply BUILDING A FRONTEND APP WITH TRUFFLE 3.0 ?

There is nothing in the tutorial about how to test your application.  While the example project does contain two test files, they the same ones shown in the Truffle docs and add no value.

**Comment by DiscRiskandBisque** [comment]
Hi @MareoRaft, totally agree in spirit, and apologies for the late response. Given the age of this tutorial, we're going to keep it as-is. We title our tutorials more accurately now! :)
