### ISSUE TITLE
Petshop Tutorial - works but metamask will no longer function due to code change

### ISSUE THREAD

**Issue by dubirl** [trufflesuite/trufflesuite.com#218]
Since MetaMask have made a code change which no longer exposes the blockchain accounts by default  - when adopting a pet - it will no longer interact with metamask. The transaction on ganche complete but it does not interact with MetaMask so you cannot interact with it or see the transaction history.

Since November 4th MetaMark  have communicated that they will no longer inject web3 by default (https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8) 

Could you please suggest how the code change they have suggested could be implemented into the PetShop tutorial - anyone that tries it now will get as far as adopting the pet but will no longer be able to interact with metamask unless the changes above are implemented.

**Comment by adrianmcli** [comment]
Thx for noting this. It's on my list of things to do this week.

**Comment by dubirl** [comment]
Hi Adrian,

Thanks for the response - hopefully the code changes will be minimal and look forward to seeing how it will work  when there - I have been using this tutorial as part of my thesis in Blockchain - its been really useful and has exposed me to a lot different languages - js not being one of my strongest!


best regards

DubIrl







________________________________

**Comment by thesachinmittal** [comment]
I think, code is still not working according to the update. Please look into it. I had to run it by disabling the privacy mode.
