### ISSUE TITLE
Missing development instructions

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/trufflesuite.com#231]
The README and the CONTRIBUTING guide are both lacking basic "getting started" steps.

This repo used to have [instructions](https://github.com/trufflesuite/trufflesuite.com/blob/097f7e0c63d677cd2743e51080988782e116a30c/README.md#development) for installing dependencies / running the dev server locally, but now they're gone.

**Comment by DiscRiskandBisque** [comment]
Thanks @gnidan and apologies for the late response! We got on it, [see the new guide here](https://github.com/trufflesuite/trufflesuite.com/blob/master/CONTRIBUTING.md). 😜
