### ISSUE TITLE
Versioned Docs

### ISSUE THREAD

**Issue by DiscRiskandBisque** [trufflesuite/trufflesuite.com#232]
Add a selectable version number to the documentation.

**Comment by pcowgill** [comment]
This is a significant pain point when contributing to a Truffle 4.x legacy project.

I think [Docusaurus](https://docusaurus.io/) would be a good fit for the Truffle team.

**Comment by DiscRiskandBisque** [comment]
Thanks @pcowgill we'll check it out!

**Comment by pcowgill** [comment]
@DiscRiskandBisque Great, thanks! For a while v2 of Docusaurus didn't support versioning yet, even though v1 did. It looks like it's close to being ready in v2 though (the link below about versioning in v2 was modified very recently), and I recommend v2 other than this potential issue.

https://v2.docusaurus.io/docs/versioning/
