### ISSUE TITLE
Config - compiler docs need to be updated

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/trufflesuite.com#234]
The configuration docs for the compilers:
 - Need to reflect byo updates (https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0#bring-your-own-compiler)
 - Vyper instructions?
 - External compiler settings (https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0#external-compiler-support)

**Comment by DiscRiskandBisque** [comment]
@eggplantzzz Can we merge or close this?

**Comment by eggplantzzz** [comment]
@DiscRiskandBisque So there is currently a section of the docs dedicated to the external compiler setup as well as the BYO compiler setup. We could consider adding some instructions for Vyper. I'm going to go ahead and close this issue and create a new one for Vyper.
