### ISSUE TITLE
Document `truffle init` and `truffle unbox` changes

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/trufflesuite.com#238]
Including:

- Overwrite behavior / prompts
- `--force`
- Unboxing from a branch or subdirectory

**Comment by gnidan** [comment]
(Probably just need to include this in the commands reference)

**Comment by eggplantzzz** [comment]
The release notes PR https://github.com/trufflesuite/roadmap/pull/196

The docs PR #249
