### ISSUE TITLE
both pet-shop and zeppelin tutorial's app.js have function that needs a missing event arguments

### ISSUE THREAD

**Issue by saneletm** [trufflesuite/trufflesuite.com#25]
pet-shop tutorial handleAdopt() function should take an event argument. it should be handleAdopt(event)
for the next line event.preventDefault();   and var petId = parseInt($(event.target).data('id'));  to work.

zeppelin tutorial app.js handleTransfer() function  also needs the same improvement for the subsequent  line to work.

**Comment by saneletm** [comment]
I would like to do a pull request and fix these two if its agreed that they are legitimate

**Comment by DiscRiskandBisque** [comment]
Good catch @saneletm  thank you!

No need to PR, I've modified both to explicitly pass the event (https://github.com/truffle-box/pet-shop-box/pull/8 + https://github.com/truffle-box/tutorialtoken-box/pull/9).

As always if you're still experiencing issues after these updates please re-open.

**Comment by saneletm** [comment]
awesome! thanks!
