### ISSUE TITLE
File naming error for truffle box blueprint

### ISSUE THREAD

**Issue by Windforcer** [trufflesuite/trufflesuite.com#281]
On the blueprint box link (https://truffleframework.com/boxes/blueprint) step 4 references `box-config.json` when the file name seems to be changed to `truffle-box.json`

**Comment by CruzMolina** [comment]
thanks for bringing this to attention @Windforcer ! i'm on leave right now, so feel free to submit a PR and i'll happily approve 😄

**Comment by DiscRiskandBisque** [comment]
Thanks again for bringing this up @Windforcer! This has since been fixed.
