### ISSUE TITLE
Ethtools is down

### ISSUE THREAD

**Issue by isaacsultan** [trufflesuite/trufflesuite.com#304]
The [tutorial](https://truffleframework.com/tutorials/using-infura-custom-provider
) below recommends using the EthTools Ropsten Faucet.

The recommendation should be changed to an [operational faucet](https://faucet.metamask.io/)/

**Comment by CruzMolina** [comment]
Thanks for raising this @isaacsultan !

#305 should resolve this. 🙏

**Comment by isaacsultan** [comment]
@CruzMolina You are welcome :)
