### ISSUE TITLE
Getting Started tutorial suggestion

### ISSUE THREAD

**Issue by burrrata** [trufflesuite/trufflesuite.com#307]
The [Importing dependencies via filename](https://truffleframework.com/docs/truffle/getting-started/compiling-contracts#importing-dependencies-via-file-name) section of the [Getting Started - Compiling Contracts](https://truffleframework.com/docs/truffle/getting-started/compiling-contracts) section is unclear. 

It says "To import contracts from a separate file, add the following code to your Solidity source file:". It does not however specify which file is the the Solidity source file. There's 3 .sol files in the contracts folder from the previous [Creating A Project](https://truffleframework.com/docs/truffle/getting-started/creating-a-project) section where MetaCoin was unboxed. This is confusing.

It would be great if you explained what the Solidity source file is. Thanks :)

**Comment by DiscRiskandBisque** [comment]
Hey @burrrata, sorry for the late response and thanks for this! Do you have an idea of how to word it better?

**Comment by DiscRiskandBisque** [comment]
Closing for now--if you still think this needs more clarification let us know via a new issue. Thanks!
