### ISSUE TITLE
Step numbers keep resetting in tutorial

### ISSUE THREAD

**Issue by wbt** [trufflesuite/trufflesuite.com#358]
For tutorials like https://truffleframework.com/tutorials/pet-shop , the step numbers keep resetting to 1.  

It would make more sense to have step numbers if the numbering continued.  

The status quo produces dialogs like "OK, now in step 2 (again) (again) (again)..." "Which Step 2 is that?" 

We should not worry about running out of integers, and mark the steps uniquely!

**Comment by eggplantzzz** [comment]
Hehe, yes right you are!

**Comment by eggplantzzz** [comment]
I guess I'm not too opposed to going back to 1 in new sections but that looks like it needs a "go-over". Some sections only have 1 step which is kind of weird.

**Comment by wbt** [comment]
> I guess I'm not too opposed to going back to 1 in new sections 

Have you ever tried teaching with the tutorial or going through it with a group?

**Comment by eggplantzzz** [comment]
No I haven't but I'm sure that would be a good way to test it.

**Comment by DiscRiskandBisque** [comment]
Thanks for your observation @wbt! The step count reset is intentional so that each section's steps are self-contained.
