### ISSUE TITLE
Japanese translation of Truffle Docs

### ISSUE THREAD

**Issue by ZahanWu** [trufflesuite/trufflesuite.com#402]
Hi. I translated Truffle Docs into Japanese (until GETTING STARTED section), so could you please link this on somewhere for Japanese users?

URL: https://github.com/ZahanWu/truffle-docs-ja/wiki

I'll soon update translation of the rest of the Docs(TESTING, ADVANCED, etc...).

**Comment by eggplantzzz** [comment]
@ZahanWu Wow, thanks that's amazing! Sorry for taking so long to get around to this. I'll see if we can do this.

**Comment by DiscRiskandBisque** [comment]
Hey @ZahanWu, thanks again for doing this! Truffle's docs don't have a way to support internationalization internally and I worry that we, as English speakers, couldn't maintain this. That said we want to support you by linking out to your translations. Is it possible for you to host these on your own site and we can link out via our docs?

**Comment by DiscRiskandBisque** [comment]
Closing for now, but @ZahanWu if you would allow us to link out to your docs let us know and we'll be happy to do so!

**Comment by ZahanWu** [comment]
@DiscRiskandBisque Hi, sorry for the late reply. The docs are now hosted on my GitBook (https://zahanwu.gitbook.io/truffle-docs-ja/).  Could you link this to your docs?
