### ISSUE TITLE
What is the feature mentioned in docs?

### ISSUE THREAD

**Issue by b-m-f** [trufflesuite/trufflesuite.com#419]
In the section https://github.com/trufflesuite/trufflesuite.com/blob/master/src/docs/truffle/testing/testing-your-contracts.md#speed-and-reliability-considerations of the docs, a special feature is mentioned.

Would it be possible to link to a description from the docs?

**Comment by DiscRiskandBisque** [comment]
Hi @b-m-f: apologies for the late follow-up!

Paging @gnidan @eggplantzzz , but I'm pretty sure these "features" in the sense of architectural choices, not features in the user-accessible sense.

**Comment by DiscRiskandBisque** [comment]
Yes @b-m-f that's totally correct. Put another way: it's faster because there is no block time (blocks are mined as soon as TXs are received)!
