### ISSUE TITLE
(Feature request): Allow to use non-standard config path 

### ISSUE THREAD

**Issue by earizon** [trufflesuite/trufflesuite.com#422]
The use-case for this option is as follow:

- A complex network setup exists with ethereum nodes running on Kubernetes, ... with random IPs/ports).

- An auxiliar utility wrapper script is used to query the environment and update an generated-config.js configuration file before launching truffle.

- This generated-config.js is added to ".gitignore" since it changes frequently.

- Original truffle-config.js contains sensible values useful for reference or common setups and we want to keep it in git.

An extra '--config generated-config.js' option will allow the wrapper script to indicate to truffle to use the autogenerated/non-git config. In any other scenario the standard truffle-config.js is used.

**Comment by earizon** [comment]
(wrong repo)

**Comment by CruzMolina** [comment]
Similar to trufflesuite/truffle#1879.
