### ISSUE TITLE
Code is not acting according to updated metamask policies, reference #218

### ISSUE THREAD

**Issue by thesachinmittal** [trufflesuite/trufflesuite.com#468]
The metamask privacy update, was accommodated in the code according to issue #218 . But I am still facing that problem, for help refer https://gist.github.com/bitpshr/076b164843f0414077164fe7fe3278d9#file-provider-enable-js

**Comment by DiscRiskandBisque** [comment]
Hi @thesachinmittal! Sorry for the late response. Are you still experiencing this issue and if so, can you provide more context? Did you encounter this in a tutorial or while going through our docs? Trying to determine if we should move to a product repo or keep it here.

**Comment by thesachinmittal** [comment]
Hi @DiscRiskandBisque -- thanks for getting back to me. Problem seems to have resolved. Closing the issue. 👍
