### ISSUE TITLE
Add solidity syntax highlighting in docs

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/trufflesuite.com#526]
Solidity support was just merged into Prism.js (used by trufflesuite.com) and should be pretty easy to add in to the site now: https://github.com/PrismJS/prism/pull/2031

**Comment by BboyAkers** [comment]
@adrianmcli Mind if I take this one?

**Comment by eggplantzzz** [comment]
@BboyAkers Take a swing! Thanks!
