### ISSUE TITLE
Updating the tezos testnet address

### ISSUE THREAD

**Issue by amateur-dev** [trufflesuite/trufflesuite.com#642]
In the instructions [QuickStart](https://github.com/trufflesuite/trufflesuite.com/blob/3b3dabb1a9cbd03f82c803cc76ed8c44a22e5397/src/docs/tezos/truffle/quickstart.md) the testnet address is wrong.

The updated testnet is `https://api.tez.ie/rpc/carthagenet`

Reference: `https://tezos.gitlab.io/introduction/test_networks.html`

**Comment by CruzMolina** [comment]
Thanks for opening this issue @amateur-dev !

This being resolved via #644.
