### ISSUE TITLE
Migrations require: filename or not? 

### ISSUE THREAD

**Issue by wbt** [trufflesuite/trufflesuite.com#66]
In the [migrations documentation](http://truffleframework.com/docs/getting_started/migrations), specifically in the [artifacts.require() section](http://truffleframework.com/docs/getting_started/migrations#artifacts-require-), there is a statement, emphasis original: 

> The name specified should match the **name of the contract definition** within that source file. Do not pass the name of the source file, as files can contain more than one contract.

Yet in the default and example files, filenames are specified.  At this point, I'm not completely sure if it's the examples or the documentation that should be fixed, but they are not consistent with each other and probably should be.

**Comment by bmmpxf** [comment]
Hi @wbt . The artifacts.require() should indeed match the name of the contract, not the name of the contract file. So the documentation is correct.

I believe it wasn't always that way, which accounts for the discrepancy. But we're in the process of updating our materials to use the recommended behavior. I'll dig into this, but if you'd like to point out specific discrepancies you've noted, that would help us out a lot. Apologies for the confusion.
