### ISSUE TITLE
can not compile(zeppelin-solidity has changed)

### ISSUE THREAD

**Issue by jetseter** [trufflesuite/trufflesuite.com#72]
![image](https://user-images.githubusercontent.com/7477261/35375584-8329e91e-01e2-11e8-9d59-eeb3197f061e.png)

we should install zeppelin-solidity 1.5.0

because 
1.MintableToken‘s folder has changed
2.totalSupply can not found
![image](https://user-images.githubusercontent.com/7477261/35375687-ebd5d9fa-01e2-11e8-99d3-1a78bb32eda6.png)

**Comment by bmmpxf** [comment]
Hi @jetseter . Thanks for pointing that out. We've updated the tutorial to be compatible with zeppelin-solidity 1.5.0. If you encounter more issues with the tutorial, please let us know!
