### ISSUE TITLE
how to create MetaCoin instance?

### ISSUE THREAD

**Issue by qiluge** [trufflesuite/trufflesuite.com#737]
As I execute the command follwed [quickstart](https://www.trufflesuite.com/docs/truffle/quickstart#interacting-with-the-contract), I encountered an error:
```
truffle(develop)> let instance = await MetaCoin.deployed()
Uncaught ReferenceError: MetaCoin is not defined
    at evalmachine.<anonymous>:1:9
```

So, how to create a MetaCoin instance?

**Comment by eggplantzzz** [comment]
Hey @qiluge, it sounds like you forgot to run your migrations. After you run `truffle develop` you should run `migrate` at the prompt. That will deploy the contracts and make `MetaCoin` available in that context and you should be able to do what you were trying to do. Let me know if you still have problems!

**Comment by qiluge** [comment]
@eggplantzzz thank you very much! After run migrations, it works! Thx!

**Comment by shashanksinghthakur** [comment]
Please help I am having the same error but this solution is not working
