### ISSUE TITLE
Contribution: explain how to keep box PR contributions up to date

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/trufflesuite.com#770]
When making changes to add a box the develop branch may change and the PR branch should be "rebased" against develop. However because box changes are inserting JSON entries git tools to auto rebase and resolve is not easy.

This happened with #625 and we should document the process.

**Comment by haltman-at** [comment]
@cds-amal says we should close this because the new way of doing boxes is not going to support this anyway.
