### ISSUE TITLE
Navbar Alignment is not proper

### ISSUE THREAD

**Issue by AemieJ** [trufflesuite/trufflesuite.com#779]
From screen width of 768-830px, due to high number of navbar items, the navbar doesn't remain aligned. 
![navbar-truffle-issue](https://user-images.githubusercontent.com/44139348/92012025-85c74700-ed69-11ea-8008-79b4efd1df82.png)

I want to propose 2 alternatives. 

1. Include navbar collapse from 830px and below. However, the breakpoints will then be hard to keep track of. 
2. Provide the navbar items below the icon for this particular screen set and it doesn't require extra code and breakpoints will be easy to keep track of. The demo Image for this is shown below: 

![navbar-styling-truffle](https://user-images.githubusercontent.com/44139348/92011997-7d6f0c00-ed69-11ea-8ef3-d3444c65f625.png)

**Comment by eggplantzzz** [comment]
Thanks for thoroughly testing our website's responsiveness :) This is another one for @DiscRiskandBisque.
