### ISSUE TITLE
Update MetaMask instructions in PetShop to cover situations with existing MetaMask accounts

### ISSUE THREAD

**Issue by firevenus** [trufflesuite/trufflesuite.com#789]
It should import a new Ganache account using private key after setting up Metamask custom RPC network in Pet-shop tutorial. Otherwise, the account wouldn't have enough Gas.

**Comment by DiscRiskandBisque** [comment]
Hey @firevenus! Thanks for pointing this out--we've changed the title to update our tutorial. In the meantime, you can import the account via private key as mentioned, but another possible solution for other tutorials you may encounter is to create an additional browser profile that doesn't already have your "real" account credentials.

**Comment by haltman-at** [comment]
It looks to me like we cover this case now in the blue box, so I'm closing this issue?  We're likely to rewrite this page soon regardless...
