### ISSUE TITLE
[WINDOWS 10] truffle unbox adrianmcli/truffle-next fails

### ISSUE THREAD

**Issue by BCsRock** [trufflesuite/trufflesuite.com#807]
I was trying to run the tutorial for the truffle NEXT.js as decsribed [here ](https://www.trufflesuite.com/boxes/truffle-next).

Unfortunately, the `truffle unbox` already fails. 

Please see my console output in this [gist](https://gist.github.com/BCsRock/3056d4f623add3934c0c08a8284dbb38)

Truffle Version
```
truffle version
Truffle v5.1.47 (core: 5.1.47)
Solidity v0.5.16 (solc-js)
Node v12.18.4
Web3.js v1.2.1
```

On Windows 10.

**Comment by DiscRiskandBisque** [comment]
Hi @BCsRock, is there a specific error message you get or does it just say the unbox failed?

**Comment by BCsRock** [comment]
Yeah, there is an error message, but its very long, so I put it into a github-gist. Please have a look there.

**Comment by eggplantzzz** [comment]
@BCsRock Can you provide us with a link to it?

**Comment by BCsRock** [comment]
Please see my console output in this [gist](https://gist.github.com/BCsRock/3056d4f623add3934c0c08a8284dbb38)

**Comment by eggplantzzz** [comment]
Looks like that problem is specific to that box. In the `truffle-box.json` it says it is trying to run `cd client && npm install && npm run link-contracts`. I'm pretty sure the `npm install` portion is failing. I would suggest contacting the maintainer to see if he knows anything about why the install portion would be failing for you.

**Comment by BCsRock** [comment]
Yes, it was related to the link-contracts module. I did not fix it but it seems some modification are necessary. Let's close it here. 

Thanks for hinting me to the correct direction.
