### ISSUE TITLE
Couldn't see private transactions at node 7 even after using "Private For"  - Quorum

### ISSUE THREAD

**Issue by MajjigaDeepak** [trufflesuite/trufflesuite.com#83]
HI,
I am trying to create private transactions using quorum and facing below error,

I removed private for in migrations file and tried, The transactions is public , i am able to see transactions from all nodes.

I included private for  node 7 public key as per tutorial in migrations file and tried, The transaction in private , i can only see the transaction from node 1 , i couldn't see transaction from node 7 (not expected), I couldn't see transaction from node 4 (Expected).

node 1  BigNumber { s: 1, e: 1, c: [ 29 ] }

node 7 BigNumber { s: 1, e: 0, c: [ 0 ] }

node 4 BigNumber { s: 1, e: 0, c: [ 0 ] }

I even tried private for node7,node4 still i couldn't see transaction in these nodes.

I exactly followed 
http://truffleframework.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains

Please help me in getting out of this.

**Comment by DiscRiskandBisque** [comment]
Hi @MajjigaDeepak! First of all, sorry for the insanely late reply. If you're still wondering about this, please re-open this issue on the @trufflesuite/truffle repository for them to investigate. Thank you!
