### ISSUE TITLE
Do not recommend importing from node_modules

### ISSUE THREAD

**Issue by naure** [trufflesuite/trufflesuite.com#86]
Referring to this page: http://truffleframework.com/docs/getting_started/packages-npm

It's fine to fetch dependencies using npm initially. However, smart contracts are subject to subtle bugs, so you really don't want dependencies to update automatically, even with semantic versioning. That could also bring malicious code, or invalidate audits. Developers should actually read the third party code once, then assume it won't change.

The example install command should recommend version locking like so:

    npm install --save-exact example-truffle-library

But really, it should recommend the best practice of copying the files to `contracts` or `installed_contracts`, and committing that to git.

**Comment by gnidan** [comment]
Thanks for the suggestion! Not sure that copying files is best practice - maybe it's sufficient to use exact version numbers?

Regardless, we'll add this to our backlog to review and incorporate into our docs. Thanks again!

**Comment by eggplantzzz** [comment]
I think we should close this as it is common practice enough to use npm libraries. Take [@openzeppelin](https://openzeppelin.com/) for example.

However maybe it would be worth adding a warning to people to either pin library versions or ensure that they trust their sources.

**Comment by cds-amal** [comment]
Closing for issue maintenance
