### ISSUE TITLE
Broken link in Solidity testing documentation

### ISSUE THREAD

**Issue by jmcph4** [trufflesuite/trufflesuite.com#875]
Currently, in the documentation for [Writing Tests in Solidity](https://www.trufflesuite.com/docs/truffle/testing/writing-tests-in-solidity), there is a broken link to `Assert.sol`, which makes it rather painful to find the full list of available assertions. This appears to have been introduced in 7884c2c.

**Comment by eggplantzzz** [comment]
Thanks for reporting this @jmcph4! I put in a PR to fix that [here](https://github.com/trufflesuite/trufflesuite.com/pull/877).

**Comment by DiscRiskandBisque** [comment]
Thanks @jmcph4 and @eggplantzzz ! Closing this because I've merged the PR.
