### ISSUE TITLE
Link Update in Bring Your Own CI (BYOCI) with Truffle Teams

### ISSUE THREAD

**Issue by roo-shy** [trufflesuite/trufflesuite.com#886]
On this page in blog link redirects to 404: https://www.trufflesuite.com/blog/bring-your-own-ci-byoci-with-truffle-teams

> For more detailed information on the external CI service, check out our documentation here: 
<img width="648" alt="Screen Shot 2021-01-06 at 8 41 38 AM" src="https://user-images.githubusercontent.com/13618162/103780769-0d181600-4ffb-11eb-8370-16ca56283735.png">

https://www.trufflesuite.com/docs/teams/testing/external-ci - this URL is broken and redirects to 404

**Comment by DiscRiskandBisque** [comment]
Hi @roo-shy, thank you for pointing this out. I've confirmed that the documentation link is broken and should be: [https://www.trufflesuite.com/docs/teams/builds/external-ci](https://www.trufflesuite.com/docs/teams/builds/external-ci) and fixed it with [PR #890](https://github.com/trufflesuite/trufflesuite.com/pull/890).
