### ISSUE TITLE
Pet-Shop Tutorial truffle test

### ISSUE THREAD

**Issue by msedd** [trufflesuite/trufflesuite.com#89]
truffle test didn´t work for me in the Pet-shop Tutorial

```
truffle(develop)> truffle test
Using network 'develop'.
  0 passing (0ms)
```
  
if I try it outside of the running truffle env:

```
$ truffle test
Could not connect to your Ethereum client. Please check that your Ethereum client:
```

I´ve created a javascript file:

```
$truffle create test TestAdoption
```
and have added the first line into the generated file

```
var TestAdoption = artifacts.require("./TestAdoption.sol");
```

now the tests are running, but I get a new error:

```
truffle(develop)> test
Using network 'develop'.

Compiling ./contracts/Adoption.sol...
Compiling ./test/TestAdoption.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...


  TestAdoption
    ✓ testUserCanAdoptPet (59ms)
    ✓ testGetAdopterAddressByPetId (47ms)
    ✓ testGetAdopterAddressByPetIdInArray (90ms)

  Contract: TestAdoption
    ✓ should assert true


  4 passing (799ms)

truffle(develop)> Error: TestAdoption has not been deployed to detected network (network/artifact mismatch)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:454:1
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

```

**Comment by ZainaliSyed** [comment]
I am also getting same sort of Error : 

Error: Election has not been deployed to detected network (network/artifact mismatch)
 at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:454:1

- I have install truffle in `npm install truffle -g` and in my project as well in node_modules `npm install truffle -dev`
- Truffle v4.1.13 - a development framework for Ethereum

**Comment by DiscRiskandBisque** [comment]
Hey @msedd! Sorry for the extremely late reply. I'm closing this due to its age, and the fact that the Pet Shop tutorial has gone through a few iterations since 2018. If this issue persists please re-open, thanks!
