### ISSUE TITLE
Have a puzzle, how can 'deployer.deploy' soothsaying contract address

### ISSUE THREAD

**Issue by code-brewer** [trufflesuite/trufflesuite.com#893]
[https://www.trufflesuite.com/docs/truffle/getting-started/running-migrations#deployer-deploy-contract-args-options-](https://www.trufflesuite.com/docs/truffle/getting-started/running-migrations#deployer-deploy-contract-args-options-)

The doc says: 
> "This will set the address of the contract after deployment (i.e., Contract.address will equal the newly deployed address), and it will override any previous address stored."

As I have known, the contract address is unknown before deployment, and decided by EVM, it is unpredictable. 

I just wonder how trufflesuite make it ?

Thanks for any light shed on it.

**Comment by eggplantzzz** [comment]
What this means is that your contract will have its address recorded in the artifact file. So after a contract is deployed, that information gets saved in the artifact in `build/contracts`. Later you can access this something like the following:
```
const MyContract =artifacts.require("MyContract");
const instance = await MyContract.deployed();
console.log(`my contract is deployed at address ${instance.address}`);
```

So before deploying the contract, there will be no address information in the artifact.
