### ISSUE TITLE
Potential support page redirect to Zendesk

### ISSUE THREAD

**Issue by roo-shy** [trufflesuite/trufflesuite.com#897]
@DiscRiskandBisque regarding your comment in [slack](https://consensys.slack.com/archives/C01L0NZJRDW/p1611346945029300?thread_ts=1611314298.017400&cid=C01L0NZJRDW)

> For the website we could even remove our other options and just direct people to ZenHub when they click the support link. In an ideal world I'd see our Community navbar link going to the Truffle Discourse and the Support link going to ZenDesk.

There is an email address that redirects to Zendesk support: support@trufflesuite.zendesk.com maybe add it for now temporary before help desk is ready. This email can also be different, we can add alias to it, for example: support@trufflesuite.com 

https://www.trufflesuite.com/docs/teams/support/ask-us-a-question

**Comment by gnidan** [comment]
This is done!
