### ISSUE TITLE
Track clicks on Support nav item

### ISSUE THREAD

**Issue by DiscRiskandBisque** [trufflesuite/trufflesuite.com#920]
The Customer Success team has requested we track clicks on the SUPPORT nav item in Teams to better see how our supplemental materials are helping users. The thinking goes: if the number of clicks on that link vs. the number of tickets open remains wide, we're adding the right content to our docs/FAQ/etc.

**Comment by gnidan** [comment]
@roo-shy says this issue is "no longer relevant", so I guess we can close! (@roo-shy, please reach out to us if you want us to implement tracking of this kind in the future)
