### ISSUE TITLE
Remaining Teams Doc Issues

### ISSUE THREAD

**Issue by DiscRiskandBisque** [trufflesuite/trufflesuite.com#927]
Here as a reminder; these could be broken down further in the future.

- Quickstart > Deploying Contracts refers to Seese's tutorial--we have deployment docs now
- Quickstart > Starting Builds could use a ref to external CI/more info
- Quickstart should go over monitoring/management as well or should have a more detailed Continue Learning section
- Builds Overview external CI could be a callout--maybe could eliminate builds overview in favor of more info in one page (currently feels fragmented)
- Sandbox forking and overview could use a re-org. Rest of the docs are fucntional and forking is a mixture of info and function which slows me down if "I'm just trying to fork"

**Comment by gnidan** [comment]
Closing this for issue maintenance.
