### ISSUE TITLE
Want to translate the site to Chinese Version.

### ISSUE THREAD

**Issue by justinchou** [trufflesuite/trufflesuite.com#93]
I am really interested in truffle and ganache, but i find there's little docs about it in Chinese. So I want have it translated to Chinese. Is this Allowed?

**Comment by bmmpxf** [comment]
Hi Justin. Thanks for your interest! Documentation help is _always_ appreciated.

I think a good first step would be to host your translation documentation somewhere else, and we'd be happy to link to it on our official docs. Over time, if we can integrate our processes sufficiently, we might be able to host your content as part of our official site. But let's start out with a link. Sound good?

**Comment by bmmpxf** [comment]
Closing this for organizational reasons, but feel free to respond here.
