### ISSUE TITLE
Please update <DrizzleProvider> with <DrizzleContext.Provider> 

### ISSUE THREAD

**Issue by roo-shy** [trufflesuite/trufflesuite.com#954]
While following [Drizzle and Contract Events | Tutorials | Truffle Suite](https://www.trufflesuite.com/tutorials/drizzle-and-contract-events) it looks like the instructions at the "Connect the Store" step is out of date. 

The drizzle box is no longer uses <DrizzleProvider>, and now uses <DrizzleContext.Provider> in `App.js`, this step should incorporate 'store' in constructing the 'drizzle' variable instead of passing store as props. 

### Connect the Store (update)
Send the store as a prop to DrizzleProvider

```
// App.js
...
import store from './middleware'
const drizzle = new Drizzle(drizzleOptions, store);
...
```
 
### Connect the Store (outdated)
Send the store as a prop to DrizzleProvider

```
// App.js
...
import store from './middleware'
...
<DrizzleProvider store={store} options={drizzleOptions}>
...
```

**Comment by gnidan** [comment]
Thanks for opening this @roo-shy! If you'd like to open the PR to fix this, here's the file that needs to change: https://github.com/trufflesuite/trufflesuite.com/blob/develop/src/guides/drizzle-and-contract-events.md

**Comment by roo-shy** [comment]
Thanks @gnidan I'm running into some `ssh/id_rsa` issues on my machine with pushing a commit to a remote repo > new branch. If anyone could update this file: `trufflesuite.com/blob/develop/src/guides/drizzle-and-contract-events.md` on lines 147-149. Thanks again 🙌

#Upated version: 
```
import store from './middleware'
const drizzle = new Drizzle(drizzleOptions, store);
```

**Comment by roo-shy** [comment]
Opened PR #[982](https://github.com/trufflesuite/trufflesuite.com/pull/982)

**Comment by haltman-at** [comment]
PR's been merged, closing this!
