### ISSUE TITLE
Broken links for guides on Drizzel Page

### ISSUE THREAD

**Issue by lsqproduction** [trufflesuite/trufflesuite.com#959]
<img width="832" alt="Screen Shot 2021-04-21 at 12 30 20 PM" src="https://user-images.githubusercontent.com/12772017/115589204-32245200-a295-11eb-8314-a4a86e3b4a8c.png">

These two guides on this page [https://www.trufflesuite.com/docs/drizzle/overview](https://www.trufflesuite.com/docs/drizzle/overview) have broken links.

**Comment by gnidan** [comment]
Looks like this got fixed!
