### ISSUE TITLE
The "Guides" section of the docs links to localhost instad of trufflesuite.com

### ISSUE THREAD

**Issue by ilmoi** [trufflesuite/trufflesuite.com#963]
Currently the "Guides" section of the truffle docs incorrectly links to the following:
```
http://localhost:9000/guides/debugging-a-smart-contract
http://localhost:9000/guides/debugger-variable-inspection
http://localhost:9000/guides/using-infura-custom-provider
http://localhost:9000/guides/using-infura-custom-provider
http://localhost:9000/guides/deploying-to-the-live-network
http://localhost:9000/guides/creating-a-cli-with-truffle-3
```

Instead of correctly linking to eg `https://www.trufflesuite.com/guides/debugging-a-smart-contract`

I was trying to find a way to fix it, but couldn't figure it out. I found [this file](https://github.com/trufflesuite/trufflesuite.com/blob/develop/src/docs/data.json) whicih I think is responsible for the outline, but it doesn't seem to list any urls.

If someone points me to files that have to be edited, happy to contribute.

Edit: same problem in ganache and drizzle guides section.

**Comment by eggplantzzz** [comment]
When I go to https://www.trufflesuite.com/guides and look at the links, they link to trufflesuite.com. Perhaps you are running the build locally? In that case they will be linked to localhost because that is where the server runs. If you can link me to a page that has them mislinked then I will take a look!

**Comment by gnidan** [comment]
Looks like we can close this! @ilmoi please let us know if we missed any; happy to re-open this. Thanks for reporting this!
