### ISSUE TITLE
pet shop tutorial problem

### ISSUE THREAD

**Issue by gewuxy** [trufflesuite/trufflesuite.com#98]
<img width="1227" alt="2018-03-26 13 33 04" src="https://user-images.githubusercontent.com/8190691/37888568-c1f7b512-30fa-11e8-9734-8e953707be81.png">
it seems that the pets are not loaded

**Comment by gewuxy** [comment]
I follow this link: http://truffleframework.com/tutorials/pet-shop

**Comment by Purple90** [comment]
I would try different browsers or in a browser that doesn't save cache (try incognito mode?). Unless you went and changed some of the CSS, I don't see why you should have issues rendering the actually website.

**Comment by DiscRiskandBisque** [comment]
Hey @gewuxy! Sorry for the extremely late reply. I'm closing this due to its age, and the fact that the Pet Shop tutorial has gone through a few iterations since 2018. If this issue persists please re-open, thanks!
