### ISSUE TITLE
Ethereum Overview link returns 404 Page

### ISSUE THREAD

**Issue by dev-waleed** [trufflesuite/trufflesuite.com#988]
On this page [https://www.trufflesuite.com/docs/truffle/quickstart](url) ; the "Ethereum Overeview" link which takes to this page [https://www.trufflesuite.com/tutorials/ethereum-overview](url) shows a 404 Page.

**Comment by haltman-at** [comment]
Ah, thanks for pointing this out -- a number of our tutorials have been moved, and it seems we missed some links.  We'll fix this.

**Comment by mongolsteppe** [comment]
I still get the wrong /tutorials/ link [here](https://www.trufflesuite.com/docs/truffle/quickstart) for 'Ethereum overview' even if in the repo file https://github.com/trufflesuite/trufflesuite.com/tree/develop/src/docs/truffle it points to the right /guide/ URL (develop and master branches). What gives?

**Comment by haltman-at** [comment]
Oh, yikes, I guess something is wrong with the publish?  @gnidan, do you know anything about this?  Or who's the right person to ask here?  Is this a problem for @kevinbluer?

**Comment by mongolsteppe** [comment]
Found the same issue at the bottom of the quickstart page 

This is what's on the repo in quickstart.md
![image](https://user-images.githubusercontent.com/75075420/121598649-b2bc2f00-ca4a-11eb-8e9a-9585bdd87fde.png)

This is what shows up in the site (guides link missing and tutorials points at an 404 URL -should be /tutorial/)
![image](https://user-images.githubusercontent.com/75075420/121598771-d1222a80-ca4a-11eb-8a4a-214ac86d71f5.png)

**Comment by haltman-at** [comment]
Yes, if the publish is broken then that will affect everything!  I'll go create a new issue for that...
